/**
 * @file save-history.js
 * @description
 * Build lifecycle script for preserving Allure test execution history and trend charts.
 * Copies the accumulated `history/` directory from the previous `allure-report/` directory
 * into the current `allure-results/` directory prior to generating a fresh Allure report.
 *
 * Responsibilities:
 * - Recursively clone the previous report's `history` directory into the active `allure-results` folder.
 * - Enable Allure to calculate trends, duration graphs, and historical flake rates across CI runs.
 * - Safely handle the cold-start case (first run) when no prior report history exists.
 *
 * Key Functions:
 * - {@link copyFolderSync} - Synchronous recursive directory copy utility.
 *
 * Dependencies:
 * - `fs`: Node.js built-in filesystem module.
 * - `path`: Node.js built-in path resolution module.
 *
 * Assumptions:
 * - Script is executed from the repository root or `scripts/` directory via `npm run report:generate`.
 *
 * Side Effects:
 * - Creates or overwrites files in the `allure-results/history` directory.
 *
 * Usage Considerations:
 * - Safe to run unconditionally; does nothing if `allure-report/history` does not exist.
 */

const fs = require('fs');
const path = require('path');

/** Path to the history directory generated by previous Allure runs */
const ALLURE_REPORT_HISTORY = path.join(__dirname, '..', 'allure-report', 'history');

/** Path to the incoming results history directory read during report generation */
const ALLURE_RESULTS_HISTORY = path.join(__dirname, '..', 'allure-results', 'history');

/**
 * Synchronously copies all files and nested subdirectories from a source folder to a target destination.
 *
 * @param {string} source
 *        Required.
 *        Absolute path to the source directory.
 * @param {string} target
 *        Required.
 *        Absolute path to the destination directory.
 * @returns {void}
 */
function copyFolderSync(source, target) {
  if (!fs.existsSync(target)) {
    fs.mkdirSync(target, { recursive: true });
  }

  const files = fs.readdirSync(source);
  files.forEach(file => {
    const srcPath = path.join(source, file);
    const destPath = path.join(target, file);
    const stat = fs.statSync(srcPath);

    if (stat.isDirectory()) {
      copyFolderSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  });
}

// Check if historical report trend data exists from a previous test execution
if (fs.existsSync(ALLURE_REPORT_HISTORY)) {
  console.log('📂 Copying previous Allure history for trend charts...');
  copyFolderSync(ALLURE_REPORT_HISTORY, ALLURE_RESULTS_HISTORY);
  console.log('✅ History copied successfully.');
} else {
  console.log('ℹ️ No previous Allure report history found. Skipping history copy (first run).');
}
